### PR TITLE
updating bor and heimdall versions in README

### PR DESCRIPTION
**Pull request by sreevalsanmr**

### CODE REVIEW

**Review by brixial — APPROVED** [review]

**Review by Leon-Africa — CHANGES_REQUESTED** [review]
We should instead use a group vars values for  bor_branch heimdall_branch network_version node_type network base on tag

**Review by okcan — APPROVED** [review]

**Comment by sreevalsanmr** [comment]
> We should instead use a group vars values for bor_branch heimdall_branch network_version node_type network base on tag

This repo should be cloud agnostic, refer https://wiki.polygon.technology/docs/maintain/validate/run-validator-ansible/

**Comment by Leon-Africa** [comment]
@sreevalsanmr yes the group vars only affect the params - talking about these ones here: https://github.com/maticnetwork/node-ansible/pull/48#issuecomment-1251031475 and the others load in group vars instead of extra vars

**Review by Leon-Africa — APPROVED** [review]
New branch for https://github.com/maticnetwork/node-ansible/pull/48#issuecomment-1251379055

**Pull request merged**
